
class Memoria {
    - tipoMemoria: String
    - capacidade: Integer
    - larguraBanda: Integer
    - velocidadeMemoria: Integer
}

class SaidaVideo {
    - tipo: String
    - quantidade: Integer
}

class PlacaDeVideo {
    - modelo: String
    - categoria: String
    - preco: BigDecimal
    - resolucao: String
    - energia: Integer
    - descricao: String
    - compatibilidade: Integer
    - clockBase: Double
    - clockBoost: Double
    - suporteRayTracing: Boolean
}

enum Fan{
    + ONE: int
    + DOUBLE: int 
    + TRIPLE: int
}

class Tamanho{
    - altura: Integer
    - largura: Integer
    - comprimento: Integer
}

class Fornecedor{
    - nome: String
    - cnpj: String
    - email: String
}

class Cliente{
    - nome: String
    - cpf: String
    - dataNascimento: LocalDate
    - email: String 
}

class Endereco{
    - cep: String
    - cidade: String
    - estado: String
    - bairro: String
    - numero: String
}

class EnderecoEntrega{
    - cep: String
    - cidade: String
    - estado: String
    - bairro: String
    - numero: String
}

class Lote {
    - codigo: String
    - estoque: Integer
    - dataFabricacao: LocalDate
}

class ItemPedido{
    - quantidade: Integer
    - preco: BigDecimal
}

class Pedido{
    - valoTotal: BigDecimal
    - data: LocalDate
}

class CartaoPagamento extends Pagamento{
    - numero: String
    - titular: String
    - dataValidade: LocalDate
    - cvv: String
    - cpf: String
}

class Cartao{
    - numero: String
    - titular: String
    - dataValidade: LocalDate
    - cvv: String
    - cpf: String
}

class Pix extends Pagamento{
    - chave: String
    - codigo: String
}

class Boleto extends Pagamento  {
    - codigoBarra: String
}

abstract class Pagamento{
    - valor: BigDecimal
}

enum StatusPagamento{
    + PAGO: int
    + PENDENTE: int
    + CANCELADO: int
}

class UpdateStatusPedido{
    - dataAtualizacao: LocalDateTime
}

enum StatusPedido{
    + AGUARDANDO_PAGAMENTO: int
    + PROCESSANDO: int
    + ENVIADO: int
    + ENTREGUE: int
    + CANCELADO: int
    + DEVOLVIDO: int
}

class TelefoneCliente{
    - numero: String
    - codigoArea: String
}

class TelefoneFornecedor{
    - numero: String 
    - codigoArea: String
}

class Funcionario{
    - nome: String
    - cpf: String
    - dataNascimento: LocalDate
    - email: String
    - salario: Double
}

class TelefoneFuncionario{
    - numero: String
    - codigoArea: String
}

class Usuario{
    - username: String
    - senha: String
}

enum StatusFuncionario{
    + ATIVADO: int
    + DESATIVADO: int
}

enum Perfil{
    + ADM: int
    + USER: int
}

' RELACIONAMENTOS
PlacaDeVideo "*" --> "1" Fornecedor
PlacaDeVideo "1" *--> "1" Tamanho
PlacaDeVideo "*" *--> "1" Fan
PlacaDeVideo "1" *--> "1" Memoria
PlacaDeVideo "1" *--> "*" SaidaVideo

Lote "*" --> "1" PlacaDeVideo 

Fornecedor "1" *--> "*" TelefoneFornecedor

Funcionario "1" --> "*" TelefoneFuncionario
Funcionario  "1" --> "1" Usuario
Funcionario "*" --> "1" StatusFuncionario

Cliente "1" *--> "*" Endereco
Cliente "1" --> "*" PlacaDeVideo : listaDesejos
Cliente "1" *--> "*" TelefoneCliente
Cliente "1" --> "1" Usuario
Cliente "1"*--> "1" Cartao

Usuario "*" --> "1" Perfil


Pedido "1" --> "1" ItemPedido
Pedido "1" *--> "1" EnderecoEntrega
Pedido "*" *--> "1" Cliente
Pedido "1" --> "1" Pagamento
Pedido "*" *--> "1" UpdateStatusPedido
UpdateStatusPedido "*" --> "1" StatusPedido

ItemPedido "*" --> "1" Lote

Pagamento "*" --> "1" StatusPagamento
' ANOTACOES

note bottom of Tamanho: todas as medidas em mm
note bottom of Memoria: capacidade = GB, velocidade = GBps, largurade banda = bits


@enduml